In [1]:
import numpy as np

In [25]:
def roll_zeropad(a, shift, axis=None):
    a = np.asanyarray(a)

    if shift == 0:
        return a

    if axis is None:
        n = a.size
        print(n)
        reshape = True
    else:
        n = a.shape[axis]
        reshape = False

    if np.abs(shift) > n:
        res = np.zeros_like(a)
    elif shift < 0:
        shift += n
        zeros = np.zeros_like(a.take(np.arange(n-shift), axis))
        print(zeros)
        res = np.concatenate((a.take(np.arange(n-shift, n), axis), zeros), axis)
        print(res)
    else:
        zeros = np.zeros_like(a.take(np.arange(n-shift, n), axis))
        res = np.concatenate((zeros, a.take(np.arange(n-shift), axis)), axis)

    if reshape:
        return res.reshape(a.shape)
    else:
        return res

In [26]:
a = np.array([[1,2,3],[3,4,5],[7,8,9],[2,3,4]])
a

array([[1, 2, 3],
       [3, 4, 5],
       [7, 8, 9],
       [2, 3, 4]])

In [27]:
roll_zeropad(a, -3, axis = 1)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [51]:
import math
import numpy as np
import multiprocessing
from numpy.random import randint
from numpy.linalg import norm, eigh
from numpy.fft import fft, ifft

def _ncc_c_3dim(data):
    x, y = data[0], data[1]
    # norm is correct den is correct
    den = norm(x, axis=(0, 1)) * norm(y, axis=(0, 1))
    # Why???
    if den < 1e-9:
        den = np.inf

    x_len = x.shape[0]
    print(x_len)
    fft_size = 1 << (2*x_len-1).bit_length()

    cc = ifft(fft(x, fft_size, axis=0) * np.conj(fft(y, fft_size, axis=0)), axis=0)
    cc = np.concatenate((cc[-(x_len-1):], cc[:x_len]), axis=0)

    return np.real(cc).sum(axis=-1) / den

In [52]:
data = np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]])
data

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [53]:
_ncc_c_3dim(data)

2


array([0.35846208, 0.97501687, 0.53052388])